#!/usr/bin/env python3
"""Generate the free Copfy image-command skills and their QA catalog."""

from __future__ import annotations

import json
from pathlib import Path


PLUGIN_ROOT = Path(__file__).resolve().parents[1]
SKILLS_ROOT = PLUGIN_ROOT / "skills"
GENERATED_MARKER = "<!-- Generated by scripts/generate_image_skills.py -->"


GROUPS: dict[str, str] = {
    "Ver por dentro": """
xray|Mostre o interior do tema como uma radiografia ou scanner de raios X, com estrutura interna visível.
crosssection|Faça um corte transversal limpo, revelando as camadas internas de forma plausível.
transparency|Torne a cobertura externa translúcida para revelar os componentes internos.
layered|Separe o tema em camadas flutuantes organizadas e identificáveis.
anatomy|Crie uma prancha anatômica do tema, com sistemas, partes e rótulos explicativos.
exploded|Separe todos os componentes em uma vista explodida alinhada e legível.
cutaway|Abra uma seção localizada do tema como um modelo didático de museu.
dissect|Disponha cada parte separada sobre uma superfície, como uma dissecação técnica organizada.
skeleton|Reduza o tema à sua armação, estrutura, juntas ou esqueleto conceitual.
peel|Descole parte da superfície para revelar o que existe logo abaixo dela.
mri|Represente o tema em fatias luminosas de ressonância ou tomografia.
core|Perfure visualmente até o centro e mostre sua composição em anéis ou camadas.
unbox|Abra a carcaça e faça os elementos internos flutuarem para fora de maneira organizada.
hollow|Esvazie o tema e fotografe sua carcaça pelo lado interno.
innerworkings|Mostre engrenagens, fios e peças internas em pleno funcionamento.
""",
    "Projeto e construção": """
wireframe|Reconstrua o tema como uma malha digital 3D limpa, preservando proporções e silhueta.
schematic|Crie um esquema técnico com componentes conectados e identificados.
technicaldrawing|Produza um desenho de engenharia com medidas, cotas e anotações precisas.
orthographic|Mostre vistas frontal, lateral, superior e em perspectiva do mesmo tema.
blueprint|Transforme o tema em uma planta técnica clássica branca sobre fundo azul.
patent|Crie uma ilustração de patente antiga, monocromática e com peças numeradas.
cad|Mostre o tema como um modelo CAD sobre uma grade de software de projeto.
floorplan|Interprete o tema como uma planta arquitetônica vista de cima e rotulada.
assembly|Crie instruções sequenciais de montagem no estilo móvel desmontável.
circuit|Reimagine o tema como uma placa de circuito com conexões e trilhas visíveis.
prototype|Apresente um protótipo bruto de oficina com fita, rascunhos e anotações.
spec|Monte uma ficha técnica com dimensões, materiais, tolerâncias e detalhes construtivos.
isodraft|Desenhe uma ilustração técnica isométrica sobre papel quadriculado.
napkin|Mostre a ideia original como um rascunho espontâneo feito em um guardanapo.
draft|Crie uma versão a lápis sobre mesa de desenho, com instrumentos técnicos no quadro.
""",
    "Movimentos de câmera": """
topdown|Fotografe a cena em vista superior detalhada e bem organizada.
macro|Faça um macro extremo, destacando microtexturas com nitidez e profundidade de campo curta.
aerial|Mostre a cena de muito alto, com composição de fotografia aérea ou drone.
fisheye|Aplique uma lente olho de peixe ultra-ampla com distorção curva intencional.
tiltshift|Use profundidade seletiva de tilt-shift para fazer a cena parecer uma miniatura real.
wormseye|Fotografe a partir do nível do chão, olhando dramaticamente para cima.
pov|Crie uma visão em primeira pessoa com mãos ou contexto do observador em quadro.
panorama|Expanda a cena em um panorama cinematográfico ultra-amplo.
longexposure|Aplique longa exposição com rastros de luz e movimento sedoso.
silhouette|Transforme o tema em silhueta retroiluminada contra um fundo luminoso.
goldenhour|Ilumine com luz quente de fim de tarde e sombras longas e suaves.
underwater|Coloque a câmera submersa, com raios de luz atravessando a água.
splitshot|Divida o quadro entre uma parte acima e outra abaixo da linha d'água.
turntable|Mostre uma rotação de 360 graus em vários quadros organizados numa grade.
freeze|Congele uma ação muito rápida no ar, com respingos ou partículas nítidas.
""",
    "Produto e estúdio": """
productshot|Crie uma fotografia comercial polida com iluminação profissional de estúdio.
packshot|Produza uma imagem limpa de e-commerce sobre fundo branco contínuo.
heroshot|Faça uma imagem principal dramática para lançamento ou página de produto.
flatlay|Organize os elementos em uma composição vista de cima, limpa e equilibrada.
knolling|Desmonte e alinhe todas as peças em ângulos retos com espaçamento perfeito.
lifestyle|Mostre o produto em uso num ambiente realista e coerente com sua marca.
mockup|Aplique o produto ou identidade visual em embalagem, tela ou material promocional.
billboard|Exiba o tema em um grande outdoor urbano noturno e fotorealista.
unboxing|Mostre o momento de abertura da embalagem com papel, fita e acessórios.
floating|Faça o produto levitar com sombras suaves e profundidade realista.
splash|Envolva o produto em um respingo de líquido congelado no tempo.
adcreative|Monte um anúncio de alto impacto com área limpa para título e chamada.
shelf|Coloque o produto numa prateleira de varejo ao lado de concorrentes plausíveis.
catalog|Crie uma página de catálogo com vários ângulos e informações do produto.
studio|Fotografe com uma única luz dramática sobre fundo colorido controlado.
""",
    "Mundos em miniatura": """
diorama|Transforme a ideia em uma cena 3D miniaturizada, rica em detalhes.
miniature|Faça uma cena real parecer um pequeno modelo colecionável fotografado de perto.
isometric|Crie um mundo 3D isométrico fofo, com linguagem visual de videogame.
snowglobe|Coloque toda a cena dentro de um globo de neve transparente.
popup|Construa a cena como um livro pop-up feito de camadas de papel.
claymation|Modele o tema em argila artesanal no estilo animação stop-motion.
toyfigure|Transforme o tema em boneco colecionável dentro de embalagem com acessórios.
dollhouse|Mostre uma casa de bonecas aberta de frente, revelando todos os ambientes.
papercraft|Reconstrua o tema inteiramente com papel recortado, dobrado e colado.
voxel|Converta o tema em uma versão 3D de blocos voxel com estética retrô.
tinyplanet|Envolva a cena ao redor de um pequeno planeta esférico.
terrarium|Crie um ecossistema em miniatura vivendo dentro de um recipiente de vidro.
boardgame|Reimagine o tema como jogo de tabuleiro completo, com peças e cartas.
keychain|Encolha o tema e transforme-o em um chaveiro colecionável reconhecível.
plush|Transforme o tema em um brinquedo de pelúcia macio e abraçável.
""",
    "Explicação visual": """
infographic|Converta o conteúdo em um infográfico limpo, hierárquico e fácil de escanear.
diagram|Explique o conceito com um único diagrama visual simples e claro.
beforeafter|Mostre dois estados lado a lado em uma comparação clara de antes e depois.
flowchart|Organize decisões e etapas em um fluxograma visual legível.
timeline|Conte a história inteira ao longo de uma linha do tempo visual.
mindmap|Crie um mapa mental ramificado a partir de uma ideia central.
stepbystep|Divida o processo em passos numerados, cada um em seu próprio painel.
comparison|Compare recursos ou versões lado a lado em uma peça gráfica organizada.
venn|Use círculos sobrepostos para mostrar interseções entre ideias.
roadmap|Mostre marcos em um caminho visual que liga o início ao objetivo.
cheatsheet|Reúna os pontos essenciais em uma única página visual de consulta rápida.
storyboard|Transforme a narrativa em quadros sequenciais de storyboard.
dashboard|Redesenhe os dados como um painel analítico limpo e coerente.
map|Converta o assunto em um mapa ilustrado e explorável.
graph|Crie um gráfico único e expressivo que torne os números imediatamente compreensíveis.
""",
    "Visão futurista": """
holographic|Projete o tema como um holograma futurista luminoso com detalhes flutuantes.
thermal|Mostre um mapa de calor de câmera térmica com zonas de temperatura coerentes.
nightvision|Recrie a imagem como visão noturna verde, com ruído e interface de câmera.
ultraviolet|Revele padrões ocultos sob luz ultravioleta ou luz negra.
neon|Contorne o tema com neon elétrico sobre fundo preto profundo.
glitch|Aplique uma estética de falha digital e fita VHS corrompida.
cyberpunk|Reimagine o tema em um ambiente cyberpunk chuvoso e iluminado por neon.
hud|Sobreponha uma interface de caça futurista com rastreamento e leituras ao vivo.
scan|Mostre uma varredura 3D em andamento com um feixe atravessando o tema.
forcefield|Envolva o tema em um escudo energético translúcido e luminoso.
chrome|Converta as superfícies em cromo líquido altamente reflexivo.
bioluminescent|Faça o tema brilhar no escuro com bioluminescência orgânica.
aura|Crie uma aura energética colorida irradiando ao redor do tema.
vaporwave|Aplique grades pastel, pôr do sol e névoa retrô vaporwave.
satellite|Mostre uma observação por satélite ou espionagem com coordenadas e identificação na tela.
""",
    "Arquivo e investigação": """
specimen|Apresente o tema como espécime científico catalogado e fotografado em laboratório.
handwritten|Reinterprete a cena como um estudo desenhado e anotado à mão.
explodedview|Crie uma vista explodida técnica com peças separadas, alinhadas e identificadas.
stickey-notes|Cubra um painel de análise com notas adesivas conectadas ao tema e às descobertas.
thermalcam|Simule uma câmera térmica completa, incluindo escala, zonas e leituras infravermelhas.
crimeboard|Monte um mural de investigação com fotografias, fios, pistas e notas relacionadas.
museumarchive|Apresente o tema como peça rara de museu com ficha, escala e marcações de arquivo.
declassified|Transforme a cena em um documento governamental secreto recém-desclassificado.
surveillance|Recrie a cena como captura de câmera de segurança com horário e monitoramento.
evidencebag|Coloque o tema dentro de um saco de evidências policiais fotografado de cima.
labnotes|Mostre o tema numa página de caderno científico com medidas, setas e hipóteses.
newspaper|Coloque o tema na primeira página de um jornal antigo como descoberta histórica.
microscope|Destaque partes do tema em ampliações circulares semelhantes a microscopia.
catalog1998|Crie uma página de catálogo comercial de 1998 com preço e especificações de época.
instructionmanual|Monte um manual com pequenos desenhos sequenciais de uso ou montagem.
assemblyline|Mostre o tema em estágios sucessivos de fabricação numa linha industrial.
beforeafterlab|Crie uma comparação científica de antes e depois com medições técnicas.
fieldguide|Apresente o tema como espécie observada na natureza dentro de um guia de campo.
archeology|Trate o tema como artefato recém-descoberto numa escavação arqueológica.
restoration|Divida o tema entre estado deteriorado e restaurado como uma peça histórica.
contactsheet|Crie uma folha de contato fotográfica com ângulos e distâncias variados.
polaroidwall|Monte uma parede de Polaroids, cada foto destacando um detalhe diferente.
redacted|Crie um documento parcialmente censurado com tarjas pretas e fragmentos visuais.
classifiedfile|Apresente o tema num arquivo confidencial com foto, carimbos e observações sigilosas.
detectivefile|Monte uma pasta de investigador com fotos, mapas, evidências e anotações.
forensic|Produza uma análise forense detalhada com escala, medidas e marcadores numerados.
airportscanner|Mostre o tema passando por um scanner de raios X de aeroporto.
diagnostic|Crie uma tela técnica que identifica componentes, falhas e estados do tema.
dataoverlay|Mantenha a fotografia realista e sobreponha dados e gráficos conectados ao tema.
scanlines|Mostre uma digitalização tridimensional em andamento com linhas de varredura.
""",
    "Protótipos e conceitos": """
polygon|Reconstrua o tema como um modelo 3D low-poly, preservando sua forma reconhecível.
clayprototype|Transforme o tema em um protótipo físico de argila ou massa de modelagem.
foamprototype|Apresente o tema como primeiro protótipo de design feito de espuma branca.
cardboardprototype|Recrie o tema com papelão, fita, cola e materiais improvisados.
origami|Interprete o tema como uma construção complexa de origami, mantendo sua silhueta.
evolution|Mostre uma sequência visual da evolução do tema, da versão primitiva à atual.
familytree|Crie uma árvore genealógica com gerações e variações imaginárias do tema.
futureartifact|Transforme o tema atual em uma relíquia encontrada milhares de anos no futuro.
alienresearch|Mostre o tema sendo estudado por uma civilização extraterrestre.
reverseengineering|Desmonte o tema em camadas, medidas e hipóteses sobre seu funcionamento.
dreamdiagram|Misture engenharia e sonho em um diagrama impossível, mas visualmente coerente.
impossiblemanual|Crie uma página de instruções absurdas apresentada com normalidade técnica.
parallelversions|Mostre lado a lado versões do tema vindas de universos paralelos.
""",
}


FIXTURE_LABELS = {
    "sneaker": "Tênis Nike roxo e branco",
    "redbull": "Lata Red Bull Zero",
    "rolex": "Relógio Rolex com diamantes",
    "burger": "Hambúrguer com bacon",
    "pizza": "Pizza margherita",
    "ze-gotinha": "Mascote Zé Gotinha",
    "casas-bahia": "Mascote Baianinho das Casas Bahia",
}


ZE_GOTINHA = {
    "xray", "anatomy", "skeleton", "mri", "microscope", "specimen",
    "labnotes", "beforeafterlab", "diagnostic", "dataoverlay",
}
CASAS_BAHIA = {
    "nightvision", "surveillance", "claymation", "toyfigure", "dollhouse",
    "papercraft", "voxel", "plush", "origami", "evolution", "familytree",
    "alienresearch", "parallelversions", "fieldguide",
}
BURGER = {
    "crosssection", "dissect", "peel", "core", "topdown", "fisheye", "pov",
    "freeze", "thermal", "thermalcam", "stepbystep", "beforeafter",
    "instructionmanual", "impossiblemanual",
}
PIZZA = {
    "aerial", "tiltshift", "panorama", "flatlay", "catalog", "infographic",
    "flowchart", "map", "graph", "contactsheet", "polaroidwall",
}
ROLEX = {
    "macro", "silhouette", "goldenhour", "productshot", "studio", "museumarchive",
    "patent", "forensic", "evidencebag", "classifiedfile", "detectivefile",
    "reverseengineering", "futureartifact", "handwritten", "newspaper", "archeology",
    "technicaldrawing", "orthographic", "spec", "isodraft", "turntable",
    "innerworkings", "restoration",
}
SNEAKER = {
    "transparency", "layered", "exploded", "explodedview", "cutaway", "unbox",
    "hollow", "wireframe", "schematic", "blueprint", "cad",
    "assembly", "prototype", "napkin", "draft", "wormseye", "longexposure",
    "underwater", "splitshot", "knolling", "lifestyle", "unboxing", "diorama",
    "miniature", "keychain", "crimeboard", "redacted", "airportscanner", "scanlines",
    "polygon", "clayprototype", "foamprototype", "cardboardprototype", "floorplan",
    "circuit", "isometric", "roadmap", "storyboard", "dreamdiagram", "stickey-notes",
}


def parse_commands() -> list[dict[str, str]]:
    commands: list[dict[str, str]] = []
    seen: set[str] = set()
    for category, raw_items in GROUPS.items():
        for raw_line in raw_items.strip().splitlines():
            name, effect = raw_line.split("|", 1)
            if name in seen:
                raise ValueError(f"Comando duplicado no catálogo: {name}")
            seen.add(name)
            commands.append({"name": name, "category": category, "effect": effect})
    if len(commands) != 148:
        raise ValueError(f"Esperados 148 comandos únicos; encontrados {len(commands)}")
    return commands


def fixture_for(name: str, category: str) -> str:
    if name in ZE_GOTINHA:
        return "ze-gotinha"
    if name in CASAS_BAHIA:
        return "casas-bahia"
    if name in BURGER:
        return "burger"
    if name in PIZZA:
        return "pizza"
    if name in ROLEX:
        return "rolex"
    if name in SNEAKER:
        return "sneaker"
    if category in {"Produto e estúdio", "Visão futurista", "Explicação visual"}:
        return "redbull"
    return "sneaker"


def skill_markdown(name: str, category: str, effect: str) -> str:
    description = (
        f"Gere ou edite imagens com o comando /{name}. {effect} "
        "Use quando o usuário pedir esse efeito ou invocar o comando diretamente."
    )
    return f"""---
name: {name}
description: {json.dumps(description, ensure_ascii=False)}
---

{GENERATED_MARKER}

# /{name}

Produza ou edite uma imagem aplicando este efeito visual:

> {effect}

**Disponibilidade:** grátis, sem autenticação Copfy.

## Exemplo visual

![Exemplo do comando /{name}](https://raw.githubusercontent.com/copfybr/copfy-plugin/main/plugins/copfy/assets/examples/{name}.jpg)

Quando o comando vier de uma recomendação, o usuário já deve ter visto esta prévia. Em uma invocação direta, gere sem criar uma etapa de confirmação desnecessária.

## Execução

1. Use a imagem anexada como referência principal. Se houver apenas uma descrição textual, gere o tema descrito.
2. Preserve a identidade, a silhueta, as cores e os elementos reconhecíveis da referência, exceto quando o próprio efeito exigir transformação.
3. Aplique o efeito de forma inequívoca, com composição, iluminação, materiais e interface coerentes com `{name}`.
4. Quando o efeito usar textos ou rótulos, mantenha-os curtos, legíveis e no idioma do usuário. Não altere logotipos ou textos essenciais sem pedido explícito.
5. Use a ferramenta nativa disponível para geração ou edição de imagens e entregue a imagem; não responda apenas com um prompt quando a ferramenta estiver disponível.
6. Se o usuário empilhar outro comando, combine os dois efeitos sem perder o tema principal. Se não houver imagem nem assunto, peça uma referência curta.

Para mascotes, alimentos e objetos sem anatomia real, interprete cortes, ossos e interiores de modo conceitual, plausível e não gráfico.
"""


def write_catalog(commands: list[dict[str, str]]) -> None:
    lines = [
        "# Comandos gratuitos de imagem",
        "",
        "148 comandos únicos disponíveis como skills do plugin Copfy.",
        "",
        "As descrições foram reescritas para uso operacional. O conjunto inicial foi baseado no material de referência Scale With PB enviado para esta implementação.",
        "",
    ]
    current = None
    for command in commands:
        if command["category"] != current:
            current = command["category"]
            lines.extend(
                [
                    f"## {current}",
                    "",
                    "| Comando | Efeito | Exemplo |",
                    "| --- | --- | --- |",
                ]
            )
        lines.append(
            f"| `/{command['name']}` | {command['effect']} | "
            f"[ver imagem](assets/examples/{command['name']}.jpg) |"
        )
    (PLUGIN_ROOT / "IMAGE_COMMANDS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_gallery(commands: list[dict[str, str]]) -> None:
    lines = [
        "# Galeria dos comandos de imagem",
        "",
        "Uma prévia gerada para cada um dos 148 comandos gratuitos.",
        "Clique numa imagem para abrir o arquivo em tamanho maior.",
        "",
    ]
    current = None
    row: list[str] = []
    for command in commands:
        if command["category"] != current:
            if row:
                while len(row) < 3:
                    row.append("")
                lines.extend(["| " + " | ".join(row) + " |", ""])
                row = []
            elif current is not None and lines[-1] != "":
                lines.append("")
            current = command["category"]
            lines.extend(
                [
                    f"## {current}",
                    "",
                    "|  |  |  |",
                    "| --- | --- | --- |",
                ]
            )
        name = command["name"]
        row.append(
            f'<a href="assets/examples/{name}.jpg"><img src="assets/examples/{name}.jpg" '
            f'width="220" alt="Exemplo /{name}"></a><br><code>/{name}</code>'
        )
        if len(row) == 3:
            lines.append("| " + " | ".join(row) + " |")
            row = []
    if row:
        while len(row) < 3:
            row.append("")
        lines.append("| " + " | ".join(row) + " |")
    (PLUGIN_ROOT / "EXAMPLES.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_test_matrix(commands: list[dict[str, str]]) -> None:
    tests_root = PLUGIN_ROOT / "tests"
    tests_root.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Matriz de teste dos comandos de imagem",
        "",
        "Cada comando deve gerar uma imagem usando a referência indicada e passar por revisão visual.",
        "As imagens de referência não fazem parte do plugin público.",
        "",
        "| Comando | Referência preferida | Categoria |",
        "| --- | --- | --- |",
    ]
    for command in commands:
        fixture = fixture_for(command["name"], command["category"])
        lines.append(
            f"| `/{command['name']}` | {FIXTURE_LABELS[fixture]} | {command['category']} |"
        )
    (tests_root / "IMAGE_TEST_MATRIX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    commands = parse_commands()
    SKILLS_ROOT.mkdir(parents=True, exist_ok=True)
    for command in commands:
        skill_root = SKILLS_ROOT / command["name"]
        skill_root.mkdir(parents=True, exist_ok=True)
        (skill_root / "SKILL.md").write_text(
            skill_markdown(command["name"], command["category"], command["effect"]),
            encoding="utf-8",
        )
    write_catalog(commands)
    write_gallery(commands)
    write_test_matrix(commands)
    print(f"Geradas {len(commands)} skills de imagem.")


if __name__ == "__main__":
    main()
